# BLURRING
# methods: none, gaussian, box, kernel (define custom kernel), dual_kawase
blur:
{
  method = "dual_kawase";
  size = 10;
  strength = 3;
# default deviation is 0.84
# deviation = false;
};

# semi-transparent
blur-background = true

blur-background-frame = true
# Use fixed blur strength rather than adjusting according to window opacity.
blur-background-fixed = true

# backends: `xrender`, `glx`, `egl` or `xr_glx_hybrid`
backend = "glx";
dithered-present = false;
vsync = false;


#rules = (
    # { match = "name = 'dwm'"; opacity = 1; },
#    { match = "focused"; opacity = 1; },
#    { match = "!focused"; opacity = 0.85; },
#    { match = "tooltip"; fade = true; shadow = true; opacity = 0.5; focus = true; full-shadow = false; },
#    { match = "popup_menu"; opacity = 0.7; },
#    { match = "dropdown_menu"; opacity = 0.7; },
#    { match = "class_g = 'qutebrowser'"; shadow = true; full-shadow = true; },
#    { match = "class_g *?= 'slop'"; blur-background = false; opacity = 1; focus = true; },
#    { match = "class_g *?= 'screenkey'"; blur-background = false; opacity = 1; focus = true; }
#);

